// examples/admob-reactjs/src/App.tsx
import { useEffect, useState } from "react";
import reactLogo from "./assets/react.svg";
import {
  BannerAd,
  RewardedAd,
  showPrivacyOptionsForm,
} from "tauri-plugin-admob-api";
import "./App.css";

function App() {
  const [bannerAd, setBannerAd] = useState<BannerAd>();
  const [rewardedAd, setRewardedAd] = useState<RewardedAd>();

  const showBannerAd = async () => {
    await bannerAd?.show();
  };

  const showRewardedAd = async () => {
    try {
      await rewardedAd?.show();
      const rewardPromise = await rewardedAd?.onRewarded(async (reward) => {
        console.log("RewardedAd get reward callback:", JSON.stringify(reward));
      });
      console.log(rewardPromise?.event);
    } catch (e) {
      console.log(e);
    }
  };

  const loadAds = async () => {
    const bannerAd = new BannerAd({
      adUnitId: "ca-app-pub-3940256099942544/9214589741",
      position: "top",
    });

    const rewardedAd = new RewardedAd({
      adUnitId: "ca-app-pub-3940256099942544/5224354917",
    });

    await bannerAd.load();
    await rewardedAd.load();

    setBannerAd(bannerAd);
    setRewardedAd(rewardedAd);
  };

  useEffect(() => {
    loadAds();
  });

  return (
    <main className="container">
      <h1>Welcome to Tauri + React</h1>

      <div className="row">
        <a href="https://vite.dev" target="_blank">
          <img src="/vite.svg" className="logo vite" alt="Vite logo" />
        </a>
        <a href="https://tauri.app" target="_blank">
          <img src="/tauri.svg" className="logo tauri" alt="Tauri logo" />
        </a>
        <a href="https://react.dev" target="_blank">
          <img src={reactLogo} className="logo react" alt="React logo" />
        </a>
      </div>
      <p>Click on the Tauri, Vite, and React logos to learn more.</p>

      <div className="row">
        <button onClick={showPrivacyOptionsForm}>Show Privacy Form</button>
      </div>
      <div className="row">
        <button onClick={showBannerAd}>Show Banner Ad</button>
      </div>
      <div className="row">
        <button onClick={showRewardedAd}>Show Rewarded Ad</button>
      </div>
    </main>
  );
}

export default App;

// examples/tauri-app/src/App.svelte
<script lang="ts">
    import { BannerAd, RewardedAd, showPrivacyOptionsForm } from "tauri-plugin-admob-api";
    import Greet from "./lib/Greet.svelte";
    import { onMount } from "svelte";

    const bannerAd = new BannerAd({
        adUnitId: "ca-app-pub-3940256099942544/9214589741",
        position: "top",
    });

    const rewardedAd = new RewardedAd({
        adUnitId: "ca-app-pub-3940256099942544/5224354917",
    });

    async function showBannerAd() {
        await bannerAd.show();
    }
    async function showRewardedAd() {
        try {
            await rewardedAd.show();
            const rewardPromise = await rewardedAd.onRewarded(async (reward) => {
                console.log("RewardedAd get reward callback:", JSON.stringify(reward));
            });
            console.log(rewardPromise.event);
        } catch (e) {
            console.log(e);
        }
    }

    async function loadAds() {
        await bannerAd.load();
        await rewardedAd.load();
    }

    onMount(() => {
        console.log("the component has mounted");
        loadAds();
    });
</script>

<main class="container">
    <h1>Welcome to Tauri!</h1>

    <div class="row">
        <a href="https://vitejs.dev" target="_blank">
            <img alt="Vite Logo" class="logo vite" src="/vite.svg" />
        </a>
        <a href="https://tauri.app" target="_blank">
            <img alt="Tauri Logo" class="logo tauri" src="/tauri.svg" />
        </a>
        <a href="https://svelte.dev" target="_blank">
            <img alt="Svelte Logo" class="logo svelte" src="/svelte.svg" />
        </a>
    </div>

    <p>Click on the Tauri, Vite, and Svelte logos to learn more.</p>

    <div class="row">
        <Greet />
    </div>

    <div class="row">
        <button on:click={showPrivacyOptionsForm}>Show Privacy Form</button>
    </div>
    <div class="row">
        <button on:click={showBannerAd}>Show Banner Ad</button>
    </div>
    <div class="row">
        <button on:click={showRewardedAd}>Show Rewarded Ad</button>
    </div>
</main>

<style>
    .logo.vite:hover {
        filter: drop-shadow(0 0 2em #747bff);
    }

    .logo.svelte:hover {
        filter: drop-shadow(0 0 2em #ff3e00);
    }
</style>
